# Numpy

=> it is a python library which is used for operating and performing mathematical functions on large and multi dimentional Arrays
=> it will store only Homogenius data 


Key Features of NumPy:

    Efficient array operations
    Broadcasting (perform operations on arrays of different shapes)
    Mathematical functions (linear algebra, statistics, etc.)
    Memory-efficient(as it will not store the datatype)
    Integration with other libraries (Pandas, Matplotlib, Scikit-learn, etc.)
    



# Creation of 1D and 2D Arrays in NumPy


There are multiple ways to create 1D and 2D NumPy arrays:

   --> np.array() → Standard method
   --> np.arange() → Sequences
   --> np.linspace() → Evenly spaced values
   --> np.zeros(), np.ones(), np.full() → Constant values
   --> np.eye() → Identity matrix
   --> np.random → Random numbers
   --> np.fromfunction() → Function-based arrays

In [40]:
import numpy as np

arr1=np.array([1,2,3,4])

arr2=np.array([[1,2,3],[4,5,6]])

arr1=np.arange(1,6) #generates 1 to n-1
arr1=np.arange(2,10,2) #even numbers 2 to 10 size 2(increment)

arr2=np.arange(1,7).reshape(2,3)

arr1=np.linspace(0,10,5) #generates 5 random numbers between 0 to 10 including both 0 and 10

arr2=np.linspace(1,6,6).reshape(2,3)

arr1=np.zeros(4)
arr2=np.ones(4)

arr1=np.zeros((2,3))
arr2=np.ones((2,3))

arr1=np.eye(3) #generates identity matric


arr1=np.full(4,5)
arr2=np.full((2,3),7)

arr1=np.random.rand(5)
arr2=np.random.rand(2,3)

arr1=np.random.randint(1,10,5)
arr2=np.random.randint(1,10,(2,3))

def func(i,j):   #here i and j indicates row and column respectively 
    return i+j   # i,j goes from 0 to n-1 
arr1=np.fromfunction(func,(3,3))
#print(arr1)
#print(arr2)

# creation of 3D arrays
=> same above all methods can be used

In [38]:
arr1=np.array([
[[1,2,3],[3,4,5]],
    [[4,5,6],[5,6,7]]
]
)

arr1=np.arange(1,25).reshape((2,3,4)) #2 layers(depth),3 = rows and 4 = columns
arr1=np.ones((2,3,2))
#print(arr1)

# Properties of Arrays

In [67]:
arr1=np.array([1,2,3,4]) # it print "," to indicate as it is a tuple
arr2=np.array([[1,2,3],[3,4,5]])
#print(arr2.shape)

arr1 = np.array([1, 2, 3])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D array

#print(arr1.ndim,arr2.ndim,arr3.ndim)
#print(arr2.size) #output 6 (2x3)

arr1 = np.array([1, 2, 3])  # Integer array
arr2 = np.array([1.2, 3.4, 5.6])  # Float array
arr3 = np.array(['a', 'b', 'c'])  # String array

#print(arr1.dtype)
arr = np.array([1, 2, 3], dtype=np.int32) #as int 32 takes 4 bytes
#print(arr2.itemsize)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
#print(arr2.T)
#print(arr2.ravel()) #effect the original arr
#print(arr2.flatten()) # not effect the original array

print(arr2.min(),arr2.max(),arr2.sum())

1 6 21


# Operations on Arrays

=> Arithmetic Operations
=> Comparison Operations
=> Logical Operations
=> Aggregate Functions
=> Matrix Operations
=> Reshaping and Flattening
=> Stacking and Splitting
=> Copying vs. View

In [75]:
##Arithmetic
a1=np.array([1,2,3])
a2=np.array([1,2,3])
print(a1+a2) # simillarly - , * , / , **
print(a1+5) #adds 5 for each element in a1 array

###Comparision
print(a1==a2) # checks each element of a1 respectively with its a2 element
print(np.where(a1>1)) # returns the indies of the elements

##Logical
bool_arr1 = np.array([True, False, True, False])
bool_arr2 = np.array([False, False, True, True])
print(np.logical_and(bool_arr1,bool_arr2)) #Simillarly or and not for one array

[2 4 6]
[6 7 8]
[ True  True  True]
(array([1, 2], dtype=int64),)
[False False  True False]


In [88]:
#Aggregate Functions
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", arr.sum())  
print("Column-wise Sum:", arr.sum(axis=0))  # [5 7 9]
print("Row-wise Sum:", arr.sum(axis=1))  # [6 15]

print("Mean:", arr.mean())  # 3.5
print("Median:", np.median(arr))  # 3.5
print("Standard Deviation:", arr.std())  # 1.7078

print("Max Value:", arr.max())  # 6
print("Min Value:", arr.min())  # 1

print("Index of max:",arr.argmax()) #index in flatten array

Sum: 21
Column-wise Sum: [5 7 9]
Row-wise Sum: [ 6 15]
Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Max Value: 6
Min Value: 1
Index of max: 5


In [82]:
#Matrix operations
# 1.Dot product
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(np.dot(a1,a2)) #Matrix multiplication
#2.Transpose
#3.inverse
print(np.linalg.inv(a1))
#4.Determinant
print(np.linalg.det(a1))

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [84]:
#Stacking
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Vertical Stack:\n", np.vstack((arr1, arr2)))
print("Horizontal Stack:\n", np.hstack((arr1, arr2)))

#Splitting
arr = np.array([1, 2, 3, 4, 5, 6])
print("Split into 3 parts:", np.split(arr, 3))

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]


In [85]:
#Copying vs. View

arr = np.array([1, 2, 3])
view_arr = arr.view()
copy_arr = arr.copy()

view_arr[0] = 100
print("Original:", arr)  # [100 2 3] (Changed because it's a view)
print("Copy:", copy_arr)  # [1 2 3] (Unchanged)


Original: [100   2   3]
Copy: [1 2 3]


### Accessing is simillar by index and slicing
Fancy indexing means selecting required indices from the array and storing in one variable directly accesing it in array

# Universal Functions :
=> Arthimetic functions
=> trignometric functions 
=> Exponential and Logarithmic Functions
=> Rounding Functions
=> Statistical & Aggregation Functions
=> Comparison & Logical Functions
=> Sorting & Searching Functions
=> Unique & Counting Functions

In [89]:
#Trignometric
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])

print("Sine:", np.sin(angles))  
print("Cosine:", np.cos(angles))  
print("Tangent:", np.tan(angles))  
print("Radians to Degrees:", np.degrees(np.pi))  
print("Degrees to Radians:", np.radians(180))  

Sine: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
Cosine: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]
Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15]
Radians to Degrees: 180.0
Degrees to Radians: 3.141592653589793


In [90]:
#Exponential and logrithemic

arr = np.array([1, 2, 3, 4])

print("Exponential (e^x):", np.exp(arr))  
print("Log (Natural log):", np.log(arr))  
print("Log base 2:", np.log2(arr))  
print("Log base 10:", np.log10(arr))  


Exponential (e^x): [ 2.71828183  7.3890561  20.08553692 54.59815003]
Log (Natural log): [0.         0.69314718 1.09861229 1.38629436]
Log base 2: [0.        1.        1.5849625 2.       ]
Log base 10: [0.         0.30103    0.47712125 0.60205999]


In [91]:
#Unique and Counting functions

arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique_vals, counts = np.unique(arr, return_counts=True)

print("Unique Values:", unique_vals)  # [1 2 3 4]
print("Counts:", counts)  # [1 2 3 1]


Unique Values: [1 2 3 4]
Counts: [1 2 3 1]


#### Joining Arrays in NumPy

In [92]:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Join along axis 0 (rows)
joined_0 = np.concatenate((arr1, arr2), axis=0)
print("Joined along axis 0:\n", joined_0)

# Join along axis 1 (columns)
joined_1 = np.concatenate((arr1, arr2), axis=1)
print("Joined along axis 1:\n", joined_1)
#stack ,hstack and vstack also above mentioned

Joined along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joined along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


### Swapaxes

In [96]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape (2,2,2)

swapped = np.swapaxes(arr, 0, 1)  # Swap axis 0 and 1
print("Original Shape:", arr.shape)
print("Swapped Shape:", swapped.shape)

Original Shape: (2, 2, 2)
Swapped Shape: (2, 2, 2)


### eigenvalues, eigenvectors

In [97]:
A = np.array([[4, -2], [1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
